### ISSUE TITLE
Issue with code highlight with swagger .json files

### ISSUE THREAD

**Issue by Vinko90** [Singulink/SingulinkFX#1]
Hey guys,
we are using your template in DocFX to build a simple documentation site. However I have noticed that by importing the swagger json there is no code highlight. We get the following warnings:
![warnings](https://i.imgur.com/nEYAsH4.png "warnings")

Could you please help us out here?

**Comment by mikernet** [comment]
This is a question better suited for the docfx repo - I don't think it is related to the template. Do you get code highlighting using the default template?

**Comment by mikernet** [comment]
I haven't used docfx for generating REST API docs so I'm not entirely sure what the process is to add the lang module for that.

**Comment by Vinko90** [comment]
Thank you very much for getting back to me. 
As far as I can see the issue is either the template or the memberpage plugin. That's because if I use the "default" theme everything works as expected, including highlighting. We saw how to import the swagger json from the repo called docfx-seed, and unfortunately that also use the default theme.

I've updated a simple demo project in case you wanted to investigate as well:
[test.zip](https://github.com/Singulink/SingulinkFX/files/9010529/test.zip)

**Comment by mikernet** [comment]
I could be wrong but I don't believe you need memberpage for REST API docs, that's more for .NET APIs. See what happens without it. I'm guessing it won't have any effect on REST API doc generation but try it without and let me know.

If you still have an issue I'll investigate further.

**Comment by mikernet** [comment]
P.S. Are you using the template from this SingulinkFX repo? The one in the FileSystem repo is likely outdated.

**Comment by mikernet** [comment]
If it works with the default theme but not this theme then I mucked something up somewhere when it is used with REST APIs. I'll have a look in a bit and let you know. I made this theme for use with .NET libs so I haven't tested it with REST APIs, I'm not even sure if there will be any styling/layout issues in that situation but I can see if there's an easy fix for making it work.

**Comment by mikernet** [comment]
What highlighting are you expecting? Can you take screenshots to show the highlighting that the default theme does that mine doesn't? From what I can tell they both behave the same way.

**Comment by mikernet** [comment]
i.e. the `lang-restApi` code block that says `PUT /user/{username}` does not have highlighting on either theme.

**Comment by mikernet** [comment]
I'm closing the issue for now, but feel free to respond if you are still having a problem.
