### ISSUE TITLE
Markdown anchors not scrolling the view

### ISSUE THREAD

**Issue by TrevorMare** [Singulink/SingulinkFX#12]
The issue I am facing is that when I have anchors in an article document, they do not scroll into view when clicked. 

The issues can be summarized as the following:

The first one is that there is no <header></header> defined in the template. Line 1181 in the docfx.js file calls the getFixedOffset() method and it relies on this element to be present to calculate the offset to scroll to. This is an easy enough fix to implement and I just added it to my template.

The second issue is a bit harder, Line 1182 in the docfx.js calls the window.scrollTo() method. Due to the styling of the document, it's not the window that should scroll but rather the ".main-panel" div element. Other than completely shipping a custom docfx.js script, I am not sure how this can be fixed.

**Comment by mikernet** [comment]
Are you sure you're using the last version? I don't have any of the issues you describe.

**Comment by benborra** [comment]
Hey @mikernet I was wondering if there's an update on a potential fix?
Kind regards

**Comment by benborra** [comment]
> Hey @mikernet I was wondering if there's an update on a potential fix? Kind regards

Hi, feel free to disregard my comment, didn't realis docFX handles internal links differently.
For others reading this, add a 'uid' tag to the top of the page, and create links by using 'xref:<uid>#<header>' as a link.

Or see the documentation: https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#using-hashtag-in-cross-reference

**Comment by sliekens** [comment]
Hello, I also noticed this problem but I don't quite understand the proposed solution (or workaround?)

The issue also presents itself in the live demo: links to headers are not scrolled into view, for example:
https://www.singulink.com/Docs/Singulink.IO.FileSystem/articles/guides/getting-started.html#cross-platform-path-handling

Clicking the link should scroll to the "Cross platform path handling" section.

**Comment by TrevorMare** [comment]
Apologies, I see that I missed the element that was used for the calculation in the original post. 

The issues are as follows, in the default docfx.js file, there is a calculation for the offset used in the scrolling (templates/default/styles/docfx.js line 1160). This calculation is calling for a header element to be present.

```
    function getFixedOffset() {
      return $('header').first().height();
    }
```

But there is no such header defined in the templates. All that is required to get this part working is to add an empty header into the file [_master.tmpl](https://github.com/Singulink/SingulinkFX/blob/master/singulinkfx/layout/_master.tmpl). I added mine on line 13

```

    <body>
        <header id="head"></header> <-- Added empty Header 
        <div class="top-navbar">
           ...
```

This will fix the offset calculation error that is occurring. 

As for the second issue also in the previously mentioned docfx.js file on line 1182

```

window.scrollTo(window.pageXOffset, anchorOffset);

```

Just due to the styling applied to the site, the widow scrolling does not actually work. The quickest way (although not the best) was to clone the docfx.js script and just change the problem line to 

## docfx.scroll.js (copied)
```

$('.main-panel').scrollTo(window.pageXOffset, anchorOffset);

```

Then I just updated my [scripts.tmpl.partial](https://github.com/Singulink/SingulinkFX/blob/master/singulinkfx/partials/scripts.tmpl.partial) file to point to my adjusted docfx.js file.

```

<script type="text/javascript" src="{{_rel}}styles/docfx.scroll.js"></script>

```

**Comment by mikernet** [comment]
Fixed via https://github.com/Singulink/SingulinkFX/commit/4b729ed0ffeafd2e02f0125e0ea3a94547644db7

**Comment by benborra** [comment]
Thank you for the fix!
Installed the update this weekend.
