### ISSUE TITLE
Nested lists in markdown are hidden

### ISSUE THREAD

**Issue by TrevorMare** [Singulink/SingulinkFX#13]
When you have nested lists in an article markdown file, the children are hidden and not displayed. 

This is down to the fact that the included discord.css hides the elements on line 605. This has been reported on the git project https://github.com/jbltx/DiscordFX but the owners of the project seem a bit quiet. I am not sure if they will fix the issue.

The fix I implemented to get it working was just to add an additional selector (.sidetoc) on the css on line 605

```css
.sidetoc li > ul
{
    display: none;
}
```

**Comment by mikernet** [comment]
Thanks, implemented the fix. The goal was always to get rid of discord.css eventually but haven't had the time.

**Comment by mikernet** [comment]
New v3.0 release is published.
