### ISSUE TITLE
Not getting tree expansion...

### ISSUE THREAD

**Issue by tig** [Singulink/SingulinkFX#17]
See here: https://gui-cs.github.io/Terminal.Gui/api/Terminal.Gui/Terminal.Gui.html

In the demo the left side is a tree that expands showing members:

<img width="207" alt="image" src="https://github.com/Singulink/SingulinkFX/assets/585482/53003cc2-e9b4-4841-b1c3-682cd922a13b">

For Terminal.Gui the tree isn't working:

<img width="189" alt="image" src="https://github.com/Singulink/SingulinkFX/assets/585482/b0dbdaae-ccaa-47f6-8c6e-c58a330aac49">

How do I turn that on?

**Comment by mikernet** [comment]
You don't need to turn it on, it should just work if the metadata is being generator correctly.
Please try again with the latest docfx and latest v3.0 release of singulinkfx.
If it still does not work - does it work with the default template?

**Comment by mikernet** [comment]
Oh wait, I think you are asking about the separate member pages. Sorry, misunderstood your question.

Please refer to [the docfx.json file](https://github.com/Singulink/Singulink.IO.FileSystem/blob/master/Docs/docfx.json) for how to set it up correctly. What you are looking for is this line specifically:

https://github.com/Singulink/Singulink.IO.FileSystem/blob/master/Docs/docfx.json#L13

**Comment by tig** [comment]
> Oh wait, I think you are asking about the separate member pages. Sorry, misunderstood your question. I thought you had that set but for some reason the table of contents was broken.
> 
> Please refer to [this docfx.json file](https://github.com/Singulink/Singulink.IO.FileSystem/blob/master/Docs/docfx.json) for how to set it up correctly. What you are looking for is this line specifically:
> 
> https://github.com/Singulink/Singulink.IO.FileSystem/blob/master/Docs/docfx.json#L13

Thank you!

<img width="238" alt="image" src="https://github.com/Singulink/SingulinkFX/assets/585482/250c219c-bd47-4feb-867e-4dc57e45346e">

**Comment by mikernet** [comment]
Cool theme!

**Comment by tig** [comment]
> Cool theme!

I got a kick out of tweaking it to rep TUI with fixed-pitch type.
