### ISSUE TITLE
memberpage error

### ISSUE THREAD

**Issue by darrendelorme** [Singulink/SingulinkFX#2]
I get this error when trying to build this template with the memberpage plugin
`Error:System.IO.FileLoadException: Could not load file or assembly 'System.Memory, Version=4.0.1.1,`

I'm trying to use this template with my Unity project and would like to have methods listed in the TOC and their own pages.

**Comment by mikernet** [comment]
Does it work without this template?

**Comment by mikernet** [comment]
I'm closing the issue for now, but feel free to respond if you are still having a problem.
