### ISSUE TITLE
Inheritance level limited

### ISSUE THREAD

**Issue by Patrick8639** [Singulink/SingulinkFX#20]
Never mind, I found the answer...

**Comment by mikernet** [comment]
Pushed commit https://github.com/Singulink/SingulinkFX/commit/3d088b32c5305365d95dbd3b0f34f82a46a9555f that updates the inheritance section to arbitrary depth in a style that matches MSDN more:

![image](https://github.com/Singulink/SingulinkFX/assets/1700111/2263e89f-58c5-4b6b-8a47-5f425510e99c)
