### ISSUE TITLE
Scroll bar position of the TOC is not synchronized with the entry being shown in the content area

### ISSUE THREAD

**Issue by areisler** [Singulink/SingulinkFX#3]
I was successfully able to integrate your template into the API documentation web site of my project and could nicely make use of the described customization settings. It works so far pretty well, and way better than the docfx default template. Thanks to you guys, for this work!

I found though one annoying behavior of the TOC side bar area, which disturbs usability a lot, especially if you have a large TOC in the side bar, like in my case, which do not fit fully into the default web browser window height. This behavior does not show up when using default template only (e.g., when navigating to https://dotnet.github.io/docfx/api/Microsoft.DocAsCode.YamlSerialization.TypeInspectors.ExtensibleTypeInspectorSkeleton.html).

Here the details on the two scenarios to repro this problem. It would be great if you could fix it or give any hints on how to alternatively fix it on the client side.

## Precondition

Resize the browser window so that the bottom entries inside the side bar TOC are not in the visible area and need to be scrolled to by the user

## Scenario 1
- Scroll to one of the TOC entries, which is not visible by default and click on it to show its content on the right content area.

**Current behavior** 
Scroll bar position is changed to be at the topmost TOC entry

**Expected  behavio:** 
Scroll bar position is set in the way that the activated TOC entry remains visible in the side bar area

**Example**
- click on https://www.singulink.com/Docs/Singulink.IO.FileSystem/api/Singulink.IO.SystemExtensions.ToPath.html and observe the scroll bar jumping at the start

## Scenario 2
- Show the content of some type, whose entry in the TOC not visible due to not sufficient browser window height

**Current behavior** 
On showing a type content, the scroll bar of the TOC jumps always to the topmost position

**Expected behavior** 
On showing a type content, the scroll bar of the TOC is adjusted in the way that the TOC entry, whose content is shown in the content area, becomes visible in the TOC of the side bar area

**Example**
- navigate to https://www.singulink.com/Docs/Singulink.IO.FileSystem/api/Singulink.IO.UnauthorizedIOAccessException.-ctor.html
- observe the scroll bar being at the topmost position

## Video
To better exemplify these scenarios please see also see the attached video:
![Animation](https://user-images.githubusercontent.com/35333843/196728455-660cd9a8-db58-4c6e-81bc-c9e3aad26812.gif)

**Comment by mikernet** [comment]
I will have a look and see what I can do about this. Thanks for the report.

**Comment by mikernet** [comment]
Done :)
