### ISSUE TITLE
Search results get stuck with the first valid set of results

### ISSUE THREAD

**Issue by OscarAbraham** [Singulink/SingulinkFX#5]
After the first successful search, all the next successful searches will show the same results as the first one. New search results require for the page to be reloaded.

For example, in the [reference site from the README](https://www.singulink.com/Docs/Singulink.IO.FileSystem/index.html), if one searches for "directory", two results will be shown. Then, if one searches for "extensions", the same results for the "directory" search will be shown. Yet, if one reloads the page, and searches for "extensions", the search results will be right for that first search.

EDIT
Well, it turns out that reloading the page is not the only way to show new search results; if one changes the content of the search field without ever letting it go empty, the search results will update correctly. It's only when the search field is emptied and then filled again that the results are not updated.

**Comment by mikernet** [comment]
What browser are you using?

**Comment by mikernet** [comment]
Fixed in https://github.com/Singulink/SingulinkFX/releases/tag/v2.0.1
