### ISSUE TITLE
Bug highlight.js

### ISSUE THREAD

**Issue by kevingostomski** [Singulink/SingulinkFX#8]
I wanted to migrate the DocFx vesion from 2.59.2 to the new 2.62.1 .NET Core version. Unfortunately there is a bug with the highlight.js file, which seems to be incompatible because of the version which was upgraded in DocFx since 2.62.0. Could it be possible, that we upgrade it here too ?

See Issue https://github.com/dotnet/docfx/issues/8428

**Comment by InFTord** [comment]
You can update highlight.js manually, by updating it in scripts and head file.

**Comment by mikernet** [comment]
Just released version 2.0 of the template, which has been updated to support docfx v2.62+ :)
