### ISSUE TITLE
[Bug] New Tabs Feature broken

### ISSUE THREAD

**Issue by kevingostomski** [Singulink/SingulinkFX#9]
I upgraded the DocFX version from 2.59.2 to 2.64.0 and everything works as expected. I really like the change of the SingulinkFX changes for the Alerts look, which can now be used! Nevertheless, I think there is kind of a CSS problem with the "new" [Tabs](https://dotnet.github.io/docfx/docs/markdown.html?tabs=linux,dotnet#tabs) implementation. It looks kind of wrong, which you can see in the following. 

https://user-images.githubusercontent.com/78415305/228808454-e7fcd6df-2555-4518-a463-664f8cbe8e0e.mp4

I tested it with a complete new project setup too, and it still looks kind of wrong but the functions behind it works.

<img width="1556" alt="image" src="https://user-images.githubusercontent.com/78415305/228807027-03883047-546c-499f-b308-e303a3066c9b.png">

Would it be possible, if we could style it somehow so it looks like "real" tabs ? 

**To Reproduce**
1. Download this example: [docfx_project.zip](https://github.com/Singulink/SingulinkFX/files/11110447/docfx_project.zip)
2. docfx serve _site

**Context:**
- OS: Windows
- DocFX: 2.64.0
- SingulinkFX: 2.0.1

**Comment by mikernet** [comment]
If you or someone else would like to PR something then let me know, otherwise I will get around to this when I can for the next release.

**Comment by mikernet** [comment]
Tabs are added to v2.1 :)
